# Generated by Django 3.1 on 2021-10-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='suppier',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='addres',
            field=models.CharField(max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out')], max_length=1),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='addres',
            field=models.CharField(max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
