# Generated by Django 3.1 on 2021-12-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211012_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='cost',
        ),
    ]
